[project]
name = "tii-sync-deploy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [    
    "pymssql>=2.2.0",
    "requests>=2.25.0",
    "playwright",
    "ddddocr>=1.4.9",
    "python-dotenv>=1.0.0"
]
